import jsPDF from 'jspdf'

export function generatePayslipPDF(payslip) {
  const doc = new jsPDF()
  const content = payslip.content
  const margin = 20
  let y = margin

  const line = () => {
    doc.setDrawColor(220, 220, 220)
    doc.line(margin, y, 190, y)
    y += 6
  }

  const row = (label, value, bold = false) => {
    doc.setFontSize(10)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(80, 80, 80)
    doc.text(label, margin, y)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(20, 20, 20)
    doc.text(String(value), 140, y, { align: 'right' })
    y += 7
  }

  const sectionTitle = (title) => {
    y += 2
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(100, 100, 100)
    doc.text(title.toUpperCase(), margin, y)
    y += 5
    line()
  }

  // ── Header ───────────────────────────────────────────────
  doc.setFillColor(30, 100, 180)
  doc.rect(0, 0, 210, 36, 'F')

  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('PAYSLIP', margin, 18)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Agentic Umbrella Platform', margin, 27)

  doc.setFontSize(10)
  doc.setTextColor(200, 220, 255)
  doc.text(`Generated: ${new Date(payslip.generatedAt).toLocaleDateString('en-GB')}`, 190, 27, { align: 'right' })

  y = 50

  // ── Pay period ───────────────────────────────────────────
  sectionTitle('Pay period')
  row('Period start', new Date(content.period.start).toLocaleDateString('en-GB'))
  row('Period end', new Date(content.period.end).toLocaleDateString('en-GB'))
  row('Tax year', content.period.taxYear)
  row('Tax code', content.contractor.taxCode)
  row('NI number', content.contractor.niNumber)

  // ── Earnings ─────────────────────────────────────────────
  sectionTitle('Earnings')
  row('Hours worked', `${content.earnings.hoursWorked}h`)
  row('Hourly rate', `£${Number(content.earnings.hourlyRate).toFixed(2)}`)
  row('Gross pay', `£${Number(content.earnings.grossPay).toFixed(2)}`, true)

  // ── Deductions ───────────────────────────────────────────
  sectionTitle('Deductions')
  row('Income tax (PAYE)', `£${Number(content.deductions.incomeTax).toFixed(2)}`)
  row('Employee NI', `£${Number(content.deductions.employeeNI).toFixed(2)}`)
  row('Pension (5%)', `£${Number(content.deductions.pensionEmployee).toFixed(2)}`)
  row('Umbrella fee', `£${Number(content.deductions.umbrellaFee).toFixed(2)}`)
  if (content.deductions.studentLoan > 0) {
    row('Student loan', `£${Number(content.deductions.studentLoan).toFixed(2)}`)
  }
  row('Total deductions', `£${Number(content.deductions.total).toFixed(2)}`, true)

  // ── Employer costs ───────────────────────────────────────
  sectionTitle('Employer costs')
  row('Employer NI', `£${Number(content.employerCosts.employerNI).toFixed(2)}`)

  // ── Net pay ──────────────────────────────────────────────
  y += 4
  doc.setFillColor(240, 248, 240)
  doc.roundedRect(margin, y, 170, 22, 3, 3, 'F')
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(20, 120, 60)
  doc.text('NET PAY', margin + 6, y + 14)
  doc.setFontSize(14)
  doc.text(`£${Number(content.netPay).toFixed(2)}`, 184, y + 14, { align: 'right' })
  y += 32

  // ── Tax summary ──────────────────────────────────────────
  sectionTitle('Tax summary')
  row('Annual equivalent gross', `£${Number(content.breakdown.annualGross).toFixed(2)}`)
  row('Annual tax liability', `£${Number(content.breakdown.annualTax).toFixed(2)}`)
  row('Effective tax rate', content.breakdown.effectiveTaxRate)

  // ── Footer ───────────────────────────────────────────────
  y += 8
  line()
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(150, 150, 150)
  doc.text('This payslip was generated by Agentic Umbrella Platform. Please retain for your records.', margin, y)
  y += 5
  doc.text('For queries contact your umbrella company payroll department.', margin, y)

  // save
  const filename = `payslip-${new Date(content.period.start).toLocaleDateString('en-GB').replace(/\//g, '-')}.pdf`
  doc.save(filename)
}